# Host vars specific to localhost go in here.
# file: host_vars/localhost.yml
---
# On this machine, the path to kubectl is specific
kubernetes_kubectl_bin: /usr/local/bin/kubectl
kubernetes_expected_kubectl_version: v1.32.2
argocd_hostname: "localhost"
cluster_context: "docker-desktop"
dest_namespace: "default"
