---
- name: Ensure required packages are installed
  ansible.builtin.package:
    name: curl
    state: present

- name: Download ArgoCD CLI binary
  ansible.builtin.get_url:
    url: "https://github.com/argoproj/argo-cd/releases/download/{{ argocd_cli_version }}/argocd-linux-amd64"
    dest: "/tmp/argocd"
    mode: '0755'
    force: true

- name: Move ArgoCD CLI to install path
  ansible.builtin.command:
    cmd: mv /tmp/argocd {{ argocd_cli_install_path }}
    creates: "{{ argocd_cli_install_path }}"
  become: true

- name: Ensure ArgoCD CLI is executable
  ansible.builtin.file:
    path: "{{ argocd_cli_install_path }}"
    mode: '0755'
    state: file
  become: true

- name: Verify ArgoCD CLI version
  ansible.builtin.command:
    cmd: "{{ argocd_cli_install_path }} version --client"
  register: argocd_cli_version_result
  changed_when: false

- name: Show installed ArgoCD CLI version
  ansible.builtin.debug:
    msg: "{{ argocd_cli_version_result.stdout }}"
